### ISSUE TITLE
Bad link

### ISSUE THREAD

**Issue by milazzom** [Azure/azure-docs-cli-python#1062] opened 2018-10-07 18:01 UTC
The download PDF link at the bottom of the left-side navigation is not correct.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b233e045-b444-e6d9-7893-36a72ee4a70b
* Version Independent ID: f2c47d3a-4976-ebe4-e732-e7c18dd4bed8
* Content: [Overview of the Azure CLI](https://docs.microsoft.com/en-us/cli/azure/?view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/index.md](https://github.com/Azure/azure-docs-cli-python/blob/master/docs-ref-conceptual/index.md)
* Product: **azure**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment] 2018-10-08 17:19
Duplicate of #1030.

**Closed by sptramer** 2018-10-08 17:19 UTC
Labels: duplicate, triaged
