### ISSUE TITLE
Windows installer links appear to be broken

### ISSUE THREAD

**Issue by kobulloc-MSFT** [Azure/azure-docs-cli-python#919] opened 2018-07-03 20:56 UTC
Clicking on "Download the MSI Installer" (https://azurecliprod.azureedge.net/msi/azure-cli-2.0.41.msi) is resulting in a blob not found error:

This XML file does not appear to have any style information associated with it. The document tree is shown below.
&lt;Error&gt;
&lt;Code&gt;BlobNotFound&lt;/Code&gt;
&lt;Message&gt;
The specified blob does not exist. RequestId:000ce74d-001e-0006-620f-134d9c000000 Time:2018-07-03T20:47:14.2773601Z
&lt;/Message&gt;
&lt;/Error&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8246b90a-efb1-03ce-f642-d3eb2441fc30
* Version Independent ID: 2fdd20ef-7bd3-57bc-7957-93f4bb5377ce
* Content: [Install the Azure CLI for Windows](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/install-azure-cli-windows.md](https://github.com/Azure/azure-docs-cli-python/blob/master/docs-ref-conceptual/install-azure-cli-windows.md)
* Product: **azure**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment] 2018-07-03 21:31
This is a duplicate of #917. The 2.0.41 release is supposed to be out this afternoon, and the redirect the link points to was updated before the MSI was available.

**Closed by sptramer** 2018-07-03 21:31 UTC

**Comment by troydai** [comment] 2018-07-03 21:36
Please retry.

**Comment by kobulloc-MSFT** [comment] 2018-07-03 22:11
Thank you!  As a quick note:  I did have to clear the cache on the page that presented me the error before I could continue with the download (Click download link > End up on same blob not found error > Ctrl + F5 to clear the cache and reload the page for a successful download).
